image:
  repository: ghcr.io/tjunjie1408/fyp-fake-dcgm-exporter
  tag: latest
  pullPolicy: IfNotPresent

gpuCount: 4
nodeName: fyp-worker # Hostname label on emitted metrics

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 64Mi

serviceMonitor:
  enabled: true
  interval: 15s
